### ISSUE TITLE
`markdown_inline` latex injection

### ISSUE THREAD

**Issue by kamalsacranie** [MDeiml/tree-sitter-markdown#86] opened 2023-03-01 18:10 UTC
`markdown_inline` injection and highlighting queries don't seem to work.

**Code example**
```markdown
This is my math expression $\frac{1}{2}$.
```

**@latex tree sitter highlighting should be applied to text inside \$\$s**. Similarly, when you perform a query in TSPlayground for `(latex_block)` and capture it, there parser does not highlight anything.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/66880161/222225385-c628d466-48da-49c5-99e1-9cf26e3168c5.png">

However, if I put the block before the first heading, then the injection works but the query in TSPlayground does not.

<img width="181" alt="image" src="https://user-images.githubusercontent.com/66880161/222225503-70957656-8b40-40d3-9246-607cb2a33de6.png">

Any ideas??

**Comment by clason** [comment] 2023-03-01 18:32
What's your Neovim version?

**Comment by clason** [comment] 2023-03-01 18:33
(duplicate of #83)

**Comment by kamalsacranie** [comment] 2023-03-01 18:34
nvim version: NVIM v0.9.0-dev-2219+gf1816f9ee-dirty
tree sitter commit: 9dd1b9c

**Comment by clason** [comment] 2023-03-01 18:40
That's not a valid version. Try updating to the latest commit. (If you run the prerelease from `master`, you are expected to keep it updated constantly.)

**Comment by kamalsacranie** [comment] 2023-03-01 18:42
This is the output I get form `nvim` and `brew`
<img width="612" alt="image" src="https://user-images.githubusercontent.com/66880161/222234854-c1e063ac-811f-49a6-8b53-8af781aa936e.png">

**Comment by clason** [comment] 2023-03-01 18:43
Irrelevant; your Neovim version is too old and you need to update it. If homebrew doesn't give you the latest HEAD version, then it's useless and you need to build from source yourself (or wait until Nvim 0.9 is released).

**Closed as completed** 2023-03-01 18:47 UTC
Labels: bug
