### ISSUE TITLE
Code block not recognized as one if there is trailing space on the closing fence

### ISSUE THREAD

**Issue by kirawi** [MDeiml/tree-sitter-markdown#135] opened 2024-02-20 23:04 UTC
**Describe the bug**

Ref https://github.com/helix-editor/helix/issues/9678

**Code example**
```markdown
'''c
''' 
int i = 0;
```
Replace the single quotes with backticks and `int i = 0` will be highlighted as C.

**Expected behavior**

According to https://github.github.com/gfm/#fenced-code-blocks, trailing whitespace are ignored on the closing code fence.

**Actual behavior**

Closing fence is not recognized.

**Comment by clason** [comment] 2024-02-21 09:44
For the record, this parser implements CommonMark Spec, with only _some_ GFM extensions (that are optional but enabled by default). I would prefer to stay strict on this (and similar "softenings" of restrictions that make parsing easier).

**Comment by clason** [comment] 2024-02-21 09:47
But CommonMark also specifies that whitespace after closing fences are to be ignored, so this _should_ be fixed ([here](https://github.com/tree-sitter-grammars/tree-sitter-markdown/blob/2821521a4e6eab37b63dff6a8e169cd88554047d/tree-sitter-markdown/src/scanner.c#L418)). PR welcome!

**Comment by savetheclocktower** [comment] 2024-03-20 17:43
I can confirm that this also happens when the closing fence is followed immediately by EOF. That's an easier scenario to catch than trailing whitespace, so I might open a PR for that case specifically.

**Comment by pokey** [comment] 2024-06-14 13:38
> I can confirm that this also happens when the closing fence is followed immediately by EOF. That's an easier scenario to catch than trailing whitespace, so I might open a PR for that case specifically.

If that's easy, a fix there would be awesome, because I think that's probably a more common scenario than trailing whitespace, though obviously both would be nice to have

**Comment by pokey** [comment] 2024-06-14 13:40
I would think both should be a fairly easy fix, no? I might be missing something, but it looks like we could just check for end of file or space in addition to `\r` and `\n` in https://github.com/tree-sitter-grammars/tree-sitter-markdown/blob/7fe453beacecf02c86f7736439f238f5bb8b5c9b/tree-sitter-markdown/src/scanner.c#L418

**Closed as completed** 2024-10-19 13:59 UTC
Labels: bug
