### ISSUE TITLE
When inside $...$, $$...$$, $$$...$$$, should not only inject latex, but also wrap with an inline_formula or displayed_equation node.

### ISSUE THREAD

**Issue by haoming-li-ling** [MDeiml/tree-sitter-markdown#117] opened 2023-09-25 03:24 UTC
**Describe the bug**
`$ $` and `$$ $$` and `$$$ $$$` are not just for switching to latex, but specifically, switching to latex math environments. For this is especially important for latex snippets that are math-environment-sensitive to work.

**Code example**
```markdown
- $x^2 + y^2 = 1$
- $$x^2 + y^2 = 1$$
- $$$x^2 + y^2 = 1$$$
```

**Expected behavior**
Switch to `inline_formula` and `displayed_math` for `$ $` and `$$ $$`,`$$$ $$$` respectively.

**Actual behavior**
The node is simply `inline`, with latex injection defaulting to text mode.

**Comment by MDeiml** [comment] 2023-11-05 12:05
It is not possible to tell the injected grammar (in this case the latex grammar) what node the root node should be. The workaround used instead is that we also include the dollars in the injected range. This way the latex grammar will automatically parse everything as it should be.

For me this also seems to be working fine. Which editor are you using? Maybe the injection queries are implemented differently?

**Comment by coekfung** [comment] 2024-01-03 17:13
Yes, the highlighting works actually fine. But the problem is that some snippets plugins for latex math depend on these nodes. So it would be really useful to name these nodes with inline_formale and displayef_equation.

**Comment by coekfung** [comment] 2024-01-05 02:43
Actually this is a bug of `nvim-treesitter`, and it should be solved in `nvim-treesitter`.
https://github.com/nvim-treesitter/nvim-treesitter/pull/5857

**Comment by coekfung** [comment] 2024-01-06 03:16
After the https://github.com/nvim-treesitter/nvim-treesitter/pull/5857 has been merged, these node can be parsed normally, which solve this issue.

**Closed as completed** 2024-01-17 10:06 UTC
Labels: bug
